config/default.ini, src/scratchtocatrobat/converter/converter.py, src/scratchtocatrobat/converter/test_converter.py
There are register handlers for SayBubbleBrick and SayForBubbleBrick,
because in Catroid Constructors like: 
SayBubbleBrick(Formula msg) 
and respectively 
SayForBubbleBrick(Formula msg, Formula duration) 
are missing.
=> STCC-60 Bubble bricks

config/default.ini, src/scratchtocatrobat/converter/converter.py, src/scratchtocatrobat/converter/test_converter.py, src/scratchtocatrobat/scratch/scratch.py
Only accepting non-empty String as argument.
If there is a formula as the argument, the brick is replaced by a note brick.
Same for an empty String.
=> STCC-58: Clone bricks

config/default.ini, src/scratchtocatrobat/converter/test_converter.py
I enhanced the tests for SetPenColor, where the argument is a 
formula. Now the generated formula for every channel is checked.
I tested the implemented PenBricks and got no errors or other 
behavior than scratch, so it should be ready for deployment.
(But I am still testing them.)
=> Enhanced SetPenColor Tests

config/default.ini, src/scratchtocatrobat/converter/converter.py, src/scratchtocatrobat/converter/test_converter.py
I saw that a brick in Motion got left out.
I quickly implemented it, please have a look if this is ok.
It was also tested on the emulator.
=> Go To Sprite: Implementation and Tests

config/default.ini, src/scratchtocatrobat/converter/converter.py, src/scratchtocatrobat/converter/test_converter.py
There is no costume name brick in Scratch.
I have tested these name and number bricks in the emulator.
=> backdrop name & number, costume number

config/default.ini, src/scratchtocatrobat/converter/converter.py, src/scratchtocatrobat/converter/test_converter.py
Tested on Emulator, should be working now.
=> STCC-80: Clone fix

config/default.ini, src/scratchtocatrobat/converter/converter.py, src/scratchtocatrobat/converter/test_converter.py, src/scratchtocatrobat/scratch/scratch.py
Workaround is not that pretty and should be refactored sometime.
timer and loudness are supported as sensors of the condition of the When Sensor > Value.
If another option is chosen (momentarily only video motion) the script is replaced by a 
simple StartScript.
Value can be a formula or int. 
Everything is tested with test cases and also directly on the Smart Phone.
Please have a look at this whole thing.
=> WhenConditionTrue

config/default.ini, src/scratchtocatrobat/converter/test_converter.py, src/scratchtocatrobat/scratch/scratch.py, src/scratchtocatrobat/scratch/test_scratch.py, src/scratchtocatrobat/test_main.py, web/main.py
Added suggested changes to the failing Jython Home tests.
Decreased the Timer delay from 0.1 to 0.03.
Added Debug print in web module for Production Mode.
=> Jython home test, Timer delay, Web debug

config/default.ini, src/scratchtocatrobat/converter/converter.py, src/scratchtocatrobat/converter/test_converter.py, src/scratchtocatrobat/scratch/scratch.py
- WhenBackgroundChanges Script
- Tests for the script
- Removed test method
=> STCC-59: WhenBackgroundChanges Script

config/default.ini, src/scratchtocatrobat/converter/converter.py
followup to: https://github.com/Catrobat/ScratchToCatrobat/pull/72
=> STCC-141 Broadcast message can be a number which causes an exception

config/default.ini, src/scratchtocatrobat/scratch/scratch3visitor/test_scratch3.py
* Mostly test that blocks with simple default values get converted correctly
=> STCC-164 Basic unittests for Scratch3 look blocks

config/default.ini, src/scratchtocatrobat/converter/test_converter.py, src/scratchtocatrobat/tools/svgtopng.py, test/res/scratch/Wizard_Spells/6_changed.svg
also svg g matrix transformation is only performed if there is a global g element
=> STCC-172 tspans in svg cause errors

config/default.ini, src/scratchtocatrobat/scratch/scratch3.py, src/scratchtocatrobat/scratch/scratch3visitor/data.py, src/scratchtocatrobat/scratch/scratch3visitor/looks.py, src/scratchtocatrobat/scratch/scratch3visitor/motion.py, src/scratchtocatrobat/scratch/scratch3visitor/operator.py, src/scratchtocatrobat/scratch/scratch3visitor/pen.py, src/scratchtocatrobat/scratch/scratch3visitor/sensing.py, src/scratchtocatrobat/scratch/scratch3visitor/sound.py, src/scratchtocatrobat/scratch/scratch3visitor/visitorUtil.py
It would probably be best to merge the refactoring of the parser before this.
=> STCC-173 Add more logging to Scratch3 parser

.gitattributes, config/default.ini, src/scratchtocatrobat/converter/test_converter.py, src/scratchtocatrobat/scratch/scratch.py, src/scratchtocatrobat/scratch/scratchwebapi.py, src/scratchtocatrobat/scratch/test_scratch.py, src/scratchtocatrobat/scratch/test_scratchwebapi.py, src/scratchtocatrobat/test_main.py
=> Fixing Broken Testcases (#100)

config/default.ini, src/scratchtocatrobat/main.py, src/scratchtocatrobat/scratch/scratch3.py, src/scratchtocatrobat/scratch/scratchwebapi.py, src/scratchtocatrobat/scratch/test_scratchwebapi.py, src/scratchtocatrobat/tools/helpers.py, web/jobmonitorserver/jobmonitortcpserver.py, web/worker/converterjob.py
scratch 3 titles
fixed errors preventing executing jobs
url validation refactored
=> Develop (#107)  Changes allowing scratch 3 conversion

config/default.ini, web/converterhttpserver.py, web/converterwebapp.py, web/main.py
I tested it locally with a self signed certificate and it works (firefox tells you that the certificate can't be verified, but lets you connect anyway).
=> [STCC-195] - Configure web server to use SSL

config/default.ini, run_statistics
This pull request can be checked out any time in order to test the script for creating conversion statistics. At the moment only complete crashes are logged in more detail. For other errors and warnings it maybe makes sense to create smaller tickets. 
Any feedback is appreciated!
=> STCC-118 Add script creating statistics of conversions

config/default.ini, web/worker/jobhandler.py
Encodes the title in the job started notification so that it's valid json data, even if it contains special characters like quotes.
=> [STCC-142] Quotes in title

.github/pull_request_template.md, config/default.ini
Added a PR Request Template similar to the one paintdroid already has.
=> STCC-236-PR-Request-Template

src/scratchtocatrobat/converter/catrobat.py, src/scratchtocatrobat/converter/converter.py
Resolved this error. Also resolved an error in catrobat.py in create_formula_with_value() that caused scratch' Boolean values to crash the converter.
=> [STCC-216] Error on adding default behavior for user lists.

src/scratchtocatrobat/converter/converter.py
Restructured the clone/collision with keyboard keys script for this case.
=> [STCC-206] Attribute error when creating the mouse emulator script whenever there are no keyboard keys to convert.

src/scratchtocatrobat/converter/converter.py, src/scratchtocatrobat/converter/test_converter.py
- Implemented workaround for the 'goto [random position]' brick
- Updated related unit test
=> [STCC-234] 'goto [random position]' moves sprite off bounds frequently

config/default.ini, web/converterhttpserver.py, web/converterwebapp.py, web/main.py
Reverts to ws and http so that the TLS functionality can be provided with the reverse proxy.
Checks first if server is open before closing it at shutdown => can close normally if can't open server
This reverts commit 2573d954290ba74e4f7d0af32c41f7d36e2f3ea0.
=> [STCC-221] Revert TLS

src/scratchtocatrobat/converter/converter.py, src/scratchtocatrobat/converter/test_converter.py
Convert the 10^ block using the power block instead of the workaround.
=> STCC-244 convert 10^

src/scratchtocatrobat/scratch/test_scratchwebapi.py, src/scratchtocatrobat/tools/common_testing.py
- Updates project IDs in test data - now referring to the S2CC Scratch projects
- Eliminates raw byte test data in project descriptions
=> STCC-192 Outsource testprojects and refactor how testdata is stored

src/scratchtocatrobat/scratch/scratch.py, src/scratchtocatrobat/scratch/scratch3.py, src/scratchtocatrobat/scratch/test_scratch.py
Traverses scratch3 scripts in scratch3.py and calculates the offset of the comments to convert them to scratch2 comments.
Workaround in scratch.py that first makes a list of the offsets and the corresponding position for comments and then adds comments at those positions.
=> STCC-231 Convert Comments

README.md, config/default.ini
incrementing version number for release
=> incrementing version number
